CREATE TABLE Customers (
    CUSTOMER_ID SERIAL PRIMARY KEY ,
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    EMAIL VARCHAR(50),
    PHONE VARCHAR(50)
);
CREATE TABLE BOOKS(
 BOOK_ID SERIAL PRIMARY KEY ,
 TITTLE VARCHAR(50),
    AUTHOR VARCHAR(30),
    GENRE VARCHAR(20),
    PRICE DECIAML (20),
    STOCK_QUANTITY DECIMAL(20)

);
CREATE TABLE ORDERS (
ORDER_ID SERIAL PRIMARY KEY ,
customer_id   SERIAL FOREIGN KEY,
order_date DATE,
TOTAL_AMOUNT DECIMAL(23)
);
